# ------------------ MONGO
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-mongo
  template:
    metadata:
      labels:
        app: app-mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
# ------------------ MONGO CLUSTER SERVICE(ONLY AVAILABLE FOR INTERNAL COMMUNICATION)
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: app-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017


# ------------------ CUSTOM INGRESS SERVICE(EXPOSES FRONTEND AND BACKEND TO OUTSIDE WORLD)
---
apiVersion: v1
kind: Service
metadata:
  name: custom-ingress-service
spec:
  selector:
    app: custom-ingress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
